// This is an autogenerated file, please refrain from changing it
//----------------------------------------------------------------------------

//----------------------------------------------------------------------------
#ifndef __ACT_SERVER__VERSION_H
#define __ACT_SERVER__VERSION_H

#define __MODULE_VERSION     "V20221103"
#define __COPYRIGHT_INYR     "2013"
#define __COPYRIGHT_YEAR     "2018"
#define __SOURCE_DATE_TIME   "2018-01-10 15:58:59 +0000"

#endif // __ACT_SERVER__VERSION_H
